# Variables
@base = http://localhost:3000/api
@productId = {{CreateProduct.response.body.productId}}
@userId = {{CreateUser.response.body.id}}
@token = {{LoginUser.response.body.token}}
@productId = {{CreateFavoriteProduct.response.body.productId}}

### HearthChecked
# @name HearthChecked
GET http://localhost:3000/hearth

### CreateProduct
# @name CreateProduct
POST {{base}}/products
Content-Type: application/json

{
  "model": "iPhone 15 | Decima geração",
  "img": "http://e-commerce.com/image/exemple-1.png",
  "slide": {
    "slide1": "http://e-commerce.com/image/exemple-1.png",
    "slide2": "http://e-commerce.com/image/exemple-2.png",
    "slide3": "http://e-commerce.com/image/exemple-3.png"
  },
  "screen": "Tela 7.6 polegada",
  "processor": "Processador 5 geração",
  "memory": "8GB de memoria",
  "placeVideo": "Rayzon 4 geração",
  "price": 3786.99,
  "category": "phone"
}

### GetProducts
# @name GetProducts
GET {{base}}/products

### GetProductWithCategory
# @name GetProductsWithCategory
GET {{base}}/products/phone

### DeleteProduct
# @name DeleteProduct
DELETE {{base}}/products/{{productId}}

### CreateUser
# @name CreateUser
POST {{base}}/users/register
Content-Type: application/json

{
  "email": "matheus@gmail.com",
  "name": "matheus",
  "password": "matheus1234",
  "cep": "55386-000"
}

### LoginUser
# @name LoginUser
POST {{base}}/users/login
Content-Type: application/json

{
  "email": "matheus@gmail.com",
  "stayConnected": true,
  "password": "matheus1234"
}

### ProfileUser
# @name ProfileUser
GET {{base}}/users/profile
Authorization: Bearer {{token}}

### UpdateUserProfile
# @name UpdateUserProfile
PATCH {{base}}/users/update
Content-Type: multipart/form-data; boundary=----separate
Authorization: Bearer {{token}}

------separate
# Images for test: paimon.png | hatsune-miku.jpg
Content-Disposition: form-data; name="avatar"; filename="hatsune-miku.jpg"
Content-Type: image/png

< ./hatsune-miku.jpg
------separate
Content-Disposition: form-data; name="name"

matheus
------separate
Content-Disposition: form-data; name="cep"

55768-000
------separate--

### DeleteUser
# @name DeleteUser
DELETE {{base}}/users
Authorization: Bearer {{token}}

### CreateDeliveryProduct
# @name CreateDeliveryProduct
POST {{base}}/products/delivery
Content-Type: application/json
Authorization: Bearer {{token}}

[{
  "image": "http://localhost:3000/images/product-ex.png", 
  "name": "Product ex", 
  "price": 112010
}, {
  "image": "http://localhost:3000/images/product-plus.png", 
  "name": "Product plus", 
  "price": 95005
},  {
  "image": "http://localhost:3000/images/product-ultra.png", 
  "name": "Product ultra", 
  "price": 106080
}]

### GetDeliveryProduct
# @name GetDeliveryProduct
GET {{base}}/products/delivery
Authorization: Bearer {{token}}

### CreateFavoriteProduct
# @name CreateFavoriteProduct
POST {{base}}/products/favorite
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "image": "http://localhost:3000/images/product-ex.png", 
  "name": "Product Ultra",
  "productId": "os7938302md3i8jf473983dn",
  "price": 125000
}

### GetAllFavoriteProduct
# @name GetAllFavoriteProduct
GET {{base}}/products/favorite
Authorization: Bearer {{token}}

### GetOneFavoriteProduct
# @name GetOneFavoriteProduct
GET {{base}}/products/favorite?productId={{productId}}
Authorization: Bearer {{token}}

### DeleteFavoriteProduct
# @name DeleteFavoriteProduct
DELETE {{base}}/products/favorite/{{productId}}
Authorization: Bearer {{token}}
