services:

  mongo: 
    image: mongo:4.2.16-bionic
    ports:
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ghome
      MONGO_INITDB_ROOT_PASSWORD: ghome123
    command: --auth
    volumes:
      - ./docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: ghome
      ME_CONFIG_MONGODB_ADMINPASSWORD: ghome123
      ME_CONFIG_MONGODB_URL: mongodb://ghome:ghome123@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo-data:

